# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту tsiurupa_yev@mail.ru если сборка упала
notifications:
  email:
    recipients:
      tsiurupa_yev@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="c4fba0da-4825-4c74-b8f2-087e4ac60c9d"

jdk:
  openjdk11

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres